Table.AddColumn(#"Origem", "Status Venda", each if [Valor] > 1000 then "Alta" else "Baixa")
