Table.SelectRows(#"Origem", each [Status] = "Ativo")
