let
    Fonte = Json.Document(File.Contents("C:\Users\tutor18.ead\Desktop\OneDrive\CURSOS_LIVRES\MICROSOFT POWER BI\PBI\PROJETO_4_IMDB\filmes_imdb_tmdb.json")),
    #"Convertido para Tabela" = Table.FromList(Fonte, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Column1 Expandido" = Table.ExpandRecordColumn(#"Convertido para Tabela", "Column1", {"ID", "Titulo", "Ano", "Duracao_Min", "Generos", "Nota_Media", "Numero_Votos", "Orcamento", "Bilheteria"}, {"ID", "Titulo", "Ano", "Duracao_Min", "Generos", "Nota_Media", "Numero_Votos", "Orcamento", "Bilheteria"}),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Column1 Expandido",{{"ID", type text}, {"Titulo", type text}, {"Ano", Int64.Type}, {"Duracao_Min", Int64.Type}, {"Generos", type text}, {"Nota_Media", type number}, {"Numero_Votos", Int64.Type}, {"Orcamento", Currency.Type}, {"Bilheteria", Currency.Type}}),
    #"Generos Organizados" = Table.AddColumn(#"Tipo Alterado", "Generos_Organizado", each Text.Combine(List.Sort(Text.Split([Generos], ",")), ", "), type text)
in
    #"Generos Organizados"
