Table.RemoveColumns(#"Origem", {"Coluna1", "Coluna2"})
